### ISSUE TITLE
Plugin update fails after OpenClaw core update

### ISSUE THREAD

**Issue by jcenters** [Martian-Engineering/lossless-claw#169]
After updating OpenClaw core from 2026.3.22 to 2026.3.23-2, the lossless-claw plugin update fails with:

```
Failed to update lossless-claw: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/linuxbrew/.linuxbrew/lib/node_modules/openclaw/dist/install.runtime-Deq6Beal.js' imported from /home/linuxbrew/.linuxbrew/lib/node_modules/openclaw/dist/installs-XLSjUYkq.js
```

The plugin is installed as a global extension at `~/.openclaw/extensions/lossless-claw/` (version 0.3.0) and loads successfully. The failure only occurs during the plugin update step after OpenClaw core updates.

Steps:
1. `openclaw update` — core updates successfully
2. Plugin update step runs and fails for lossless-claw

Environment: Linux x64, npm install
