### ISSUE TITLE
afterTurn transcript reconcile fails in 0.11.1: clearStableOrphanStrippingOrdinal is not a function

### ISSUE THREAD

**Issue by dr00-eth** [Martian-Engineering/lossless-claw#713]
## Summary

After upgrading OpenClaw to 2026.5.18 with `@martian-engineering/lossless-claw@0.11.1`, a Discord channel session reset/recovery path hit an afterTurn transcript reconcile failure:

```text
[lcm] afterTurn: transcript reconcile failed for session=f8dcfe0a-78fb-4575-895a-74e6aae6d3fa sessionKey=agent:main:discord:channel:1433563133724725258: this.clearStableOrphanStrippingOrdinal is not a function
```

The same turn then hit an OpenClaw embedded session file takeover error and fell through the configured model fallback chain.

## Environment

- OpenClaw: 2026.5.18
- lossless-claw: 0.11.1
- Node runtime in OpenClaw log: 25.6.1
- Channel/session type: Discord group channel
- Agent runtime: Pi
- Primary model: `openai/gpt-5.5`
- Lossless config highlights:
  - `freshTailCount: 20`
  - `freshTailMaxTokens: 24000`
  - `summaryModel: openai/gpt-5.4-mini`
  - `expansionModel: openai/gpt-5.4-mini`
  - `statelessSessionPatterns: ["agent:main:hook:*"]`

## Evidence

Log excerpt from `/tmp/openclaw/openclaw-2026-05-19.log`:

```text
2026-05-19T11:22:33.400-05:00 [lcm] assemble: done conversation=606 session=f8dcfe0a-78fb-4575-895a-74e6aae6d3fa sessionKey=agent:main:discord:channel:1433563133724725258 ... estimatedTokens=194 ...
2026-05-19T11:22:38.943-05:00 [lcm] afterTurn: transcript reconcile failed for session=f8dcfe0a-78fb-4575-895a-74e6aae6d3fa sessionKey=agent:main:discord:channel:1433563133724725258: this.clearStableOrphanStrippingOrdinal is not a function
2026-05-19T11:22:48.805-05:00 lane task error: lane=main durationMs=17473 error="EmbeddedAttemptSessionTakeoverError: session file changed while embedded prompt lock was released: /Users/andrewmeyer/.openclaw/agents/main/sessions/f8dcfe0a-78fb-4575-895a-74e6aae6d3fa.jsonl"
```

Local package inspection:

```text
$ node -e "... count occurrences of clearStableOrphanStrippingOrdinal ..."
1: ... if(reconcile2.importedMessages>0){this.clearStableOrphanStrippingOrdinal(conversation.conversationId); ...
count=1
```

That suggests `clearStableOrphanStrippingOrdinal` is referenced in the built package but no method/function definition is present.

## Expected

The placeholder checkpoint recovery / transcript reconcile path should not throw a missing-method error. If stable orphan stripping was removed or redesigned, this call should likely be removed, guarded, or replaced with the current invalidation method.

## Actual

The afterTurn reconcile hook logs a missing function error and leaves the session in a state where the OpenClaw embedded run later reports a session file takeover. In this observed case, that caused OpenClaw to attempt configured fallback models even though the primary model itself was not unavailable.

## Notes

- Installed release `0.11.1` is currently the latest GitHub release as of 2026-05-19.
- The failure occurred after a channel reset/recovery path where Lossless had just assembled a very small context for the new session.
- I can provide the full log privately if useful; the public issue should avoid including credentials or unrelated transcript content.

**Comment by dr00-eth** [comment]
Temporary local workaround that unblocked my install while waiting for a real fix:

1. Back up the installed build file:

```sh
cp ~/.openclaw/npm/node_modules/@martian-engineering/lossless-claw/dist/index.js \
  ~/.openclaw/npm/node_modules/@martian-engineering/lossless-claw/dist/index.js.pre-clearStableOrphan-noop.bak
```

2. Patch the installed `dist/index.js` by adding a no-op method on the `LcmContextEngine` class:

```js
clearStableOrphanStrippingOrdinal(_conversationId) {}
```

I inserted it immediately before `recordRecentBootstrapImport(...)`, since that method already exists on the same class and the missing call site is:

```js
this.clearStableOrphanStrippingOrdinal(conversation.conversationId);
```

3. Restart OpenClaw so the gateway reloads the plugin.

After restart, `openclaw gateway status` and `openclaw health` were OK, and I did not see a fresh `clearStableOrphanStrippingOrdinal is not a function` error in the post-restart log window.

Important caveats:

- This is only a local mitigation, not a proper upstream fix.
- It edits installed `node_modules`, so `openclaw plugins install`, plugin updates, or reinstalling `lossless-claw` may overwrite it.
- The no-op may skip whatever stable-orphan invalidation was originally intended, but it is preferable locally to throwing during afterTurn transcript reconcile.
